package scrapping

var MapperIdxElm = map[string]int{
                "Air": 0,
                "Earth": 1,
                "Fire": 2,
                "Water": 3,
                "Time": 4,
                "Dust": 5,
                "Energy": 6,
                "Land": 7,
                "Lava": 8,
                "Mist": 9,
                "Mud": 10,
                "Pressure": 11,
                "Puddle": 12,
                "Smoke": 13,
                "Steam": 14,
                "Brick": 15,
                "Continent": 16,
                "Earthquake": 17,
                "Eruption": 18,
                "Geyser": 19,
                "Granite": 20,
                "Gunpowder": 21,
                "Heat": 22,
                "Obsidian": 23,
                "Pond": 24,
                "Stone": 25,
                "Volcano": 26,
                "Wind": 27,
                "Chimney": 28,
                "Clay": 29,
                "Explosion": 30,
                "Lake": 31,
                "Metal": 32,
                "Mountain": 33,
                "Planet": 34,
                "Plasma": 35,
                "Sand": 36,
                "Tornado": 37,
                "Wall": 38,
                "Warmth": 39,
                "Atmosphere": 40,
                "Atomic bomb": 41,
                "Avalanche": 42,
                "Beach": 43,
                "Blade": 44,
                "Boiler": 45,
                "Bullet": 46,
                "Dam": 47,
                "Desert": 48,
                "Dune": 49,
                "Firewall": 50,
                "Glass": 51,
                "Gold": 52,
                "Grenade": 53,
                "House": 54,
                "Mercury": 55,
                "Moon": 56,
                "Mountain range": 57,
                "Plow": 58,
                "River": 59,
                "Rust": 60,
                "Sandstone": 61,
                "Sandstorm": 62,
                "Sea": 63,
                "Solar system": 64,
                "Sun": 65,
                "Venus": 66,
                "Waterfall": 67,
                "Wave": 68,
                "Aquarium": 69,
                "Aurora": 70,
                "Bank": 71,
                "Black hole": 72,
                "Blender": 73,
                "Bridge": 74,
                "Cloud": 75,
                "Current": 76,
                "Eclipse": 77,
                "Factory": 78,
                "Field": 79,
                "Fireworks": 80,
                "Flood": 81,
                "Galaxy": 82,
                "Glasses": 83,
                "Gun": 84,
                "Hourglass": 85,
                "Hurricane": 86,
                "Island": 87,
                "Katana": 88,
                "Mars": 89,
                "Meteoroid": 90,
                "Mirror": 91,
                "Oasis": 92,
                "Ocean": 93,
                "Primordial soup": 94,
                "Pyramid": 95,
                "Rainbow": 96,
                "Rocket": 97,
                "Safe": 98,
                "Salt": 99,
                "Scissors": 100,
                "Sky": 101,
                "Solar cell": 102,
                "Sound": 103,
                "Space station": 104,
                "Supernova": 105,
                "Swimming pool": 106,
                "Sword": 107,
                "Telescope": 108,
                "Tide": 109,
                "Tsunami": 110,
                "Village": 111,
                "Windmill": 112,
                "Acid rain": 113,
                "Archipelago": 114,
                "Barn": 115,
                "Bayonet": 116,
                "Bell": 117,
                "Binoculars": 118,
                "City": 119,
                "Day": 120,
                "Double rainbow!": 121,
                "Electricity": 122,
                "Excalibur": 123,
                "Fence": 124,
                "Flamethrower": 125,
                "Fog": 126,
                "Galaxy cluster": 127,
                "Hangar": 128,
                "Horizon": 129,
                "Jupiter": 130,
                "Life": 131,
                "Light sword": 132,
                "Lightning": 133,
                "Meteor": 134,
                "Night": 135,
                "Paint": 136,
                "Park": 137,
                "Prism": 138,
                "Rain": 139,
                "Ruins": 140,
                "Safety glasses": 141,
                "Skyscraper": 142,
                "Space": 143,
                "Storm": 144,
                "Stun gun": 145,
                "Sunglasses": 146,
                "Swim goggles": 147,
                "Water gun": 148,
                "Alien": 149,
                "Animal": 150,
                "Bacteria": 151,
                "Clock": 152,
                "Darkness": 153,
                "Dawn": 154,
                "Death": 155,
                "Farm": 156,
                "Human": 157,
                "Light bulb": 158,
                "Magic": 159,
                "Ozone": 160,
                "Phoenix": 161,
                "Plankton": 162,
                "Robot": 163,
                "Smog": 164,
                "Snow": 165,
                "Soil": 166,
                "Spaceship": 167,
                "Star": 168,
                "Twilight": 169,
                "Universe": 170,
                "Wind turbine": 171,
                "Wire": 172,
                "Alarm clock": 173,
                "Alchemist": 174,
                "Allergy": 175,
                "Antarctica": 176,
                "Archeologist": 177,
                "Astronaut": 178,
                "Astronomer": 179,
                "Beaver": 180,
                "Bird": 181,
                "Blizzard": 182,
                "Blood": 183,
                "Butterfly": 184,
                "Cable car": 185,
                "Camel": 186,
                "Cat": 187,
                "Chain": 188,
                "Cold": 189,
                "Constellation": 190,
                "Corpse": 191,
                "Crystal ball": 192,
                "Cyborg": 193,
                "Dew": 194,
                "Domestication": 195,
                "Dynamite": 196,
                "Egg": 197,
                "Electrician": 198,
                "Family": 199,
                "Farmer": 200,
                "Firefighter": 201,
                "Fish": 202,
                "Force knight": 203,
                "Frog": 204,
                "Glacier": 205,
                "Gravestone": 206,
                "Hacker": 207,
                "Hero": 208,
                "Horse": 209,
                "Idea": 210,
                "Igloo": 211,
                "Lamp": 212,
                "Light": 213,
                "Livestock": 214,
                "Lizard": 215,
                "Love": 216,
                "Meat": 217,
                "Microscope": 218,
                "Monarch": 219,
                "Mummy": 220,
                "Organic matter": 221,
                "Painter": 222,
                "Pig": 223,
                "Plant": 224,
                "Potter": 225,
                "Sailor": 226,
                "Samurai": 227,
                "Science": 228,
                "Scorpion": 229,
                "Shuriken": 230,
                "Sickness": 231,
                "Ski goggles": 232,
                "Skier": 233,
                "Sloth": 234,
                "Snake": 235,
                "Snow globe": 236,
                "Snowball": 237,
                "Snowman": 238,
                "Starfish": 239,
                "Sundial": 240,
                "Surfer": 241,
                "Swimmer": 242,
                "Tool": 243,
                "Turtle": 244,
                "Ufo": 245,
                "Warrior": 246,
                "Watch": 247,
                "Wizard": 248,
                "Wolf": 249,
                "Airplane": 250,
                "Algae": 251,
                "Alligator": 252,
                "Angel": 253,
                "Arctic": 254,
                "Ash": 255,
                "Bacon": 256,
                "Birdcage": 257,
                "Birdhouse": 258,
                "Bone": 259,
                "Butcher": 260,
                "Cactus": 261,
                "Cage": 262,
                "Carbon dioxide": 263,
                "Carrot": 264,
                "Castle": 265,
                "Catnip": 266,
                "Cave": 267,
                "Centaur": 268,
                "Chameleon": 269,
                "Charcoal": 270,
                "Chicken": 271,
                "Chill": 272,
                "Coal": 273,
                "Computer": 274,
                "Cotton": 275,
                "Cow": 276,
                "Crow": 277,
                "Cuckoo": 278,
                "Dinosaur": 279,
                "Dog": 280,
                "Don quixote": 281,
                "Dragon": 282,
                "Duck": 283,
                "Eagle": 284,
                "Egg timer": 285,
                "Electric eel": 286,
                "Family tree": 287,
                "Firestation": 288,
                "Fishing rod": 289,
                "Flashlight": 290,
                "Flower": 291,
                "Flying fish": 292,
                "Fossil": 293,
                "Frankenstein's monster": 294,
                "Fridge": 295,
                "Garden": 296,
                "Gas": 297,
                "Ghost": 298,
                "Goat": 299,
                "Grass": 300,
                "Grave": 301,
                "Graveyard": 302,
                "Greenhouse": 303,
                "Ham": 304,
                "Hammer": 305,
                "Hedge": 306,
                "Hippo": 307,
                "Horseshoe": 308,
                "Hospital": 309,
                "Hummingbird": 310,
                "Ice": 311,
                "Iceberg": 312,
                "Ivy": 313,
                "Jerky": 314,
                "Knight": 315,
                "Lava lamp": 316,
                "Leather": 317,
                "Lens": 318,
                "Lighthouse": 319,
                "Lion": 320,
                "Liquid": 321,
                "Machine": 322,
                "Magma": 323,
                "Medusa": 324,
                "Mermaid": 325,
                "Mineral": 326,
                "Moss": 327,
                "Moth": 328,
                "Motion": 329,
                "Nest": 330,
                "Ninja": 331,
                "Ninja turtle": 332,
                "Omelette": 333,
                "Optical fiber": 334,
                "Ostrich": 335,
                "Owl": 336,
                "Oxygen": 337,
                "Peacock": 338,
                "Pegasus": 339,
                "Penguin": 340,
                "Philosophy": 341,
                "Pigeon": 342,
                "Piggy bank": 343,
                "Piranha": 344,
                "Pirate": 345,
                "Platypus": 346,
                "Pollen": 347,
                "Pottery": 348,
                "Reed": 349,
                "Ring": 350,
                "Roe": 351,
                "Rope": 352,
                "Rose": 353,
                "Saddle": 354,
                "Seagull": 355,
                "Seahorse": 356,
                "Seasickness": 357,
                "Seaweed": 358,
                "Shark": 359,
                "Sheep": 360,
                "Skeleton": 361,
                "Snowboard": 362,
                "Solid": 363,
                "Spotlight": 364,
                "Steak": 365,
                "Stethoscope": 366,
                "Story": 367,
                "Sunflower": 368,
                "Swordfish": 369,
                "Tobacco": 370,
                "Toolbox": 371,
                "Toucan": 372,
                "Tree": 373,
                "Umbrella": 374,
                "Unicorn": 375,
                "Vampire": 376,
                "Vegetable": 377,
                "Vulture": 378,
                "Wand": 379,
                "Werewolf": 380,
                "Wheel": 381,
                "Wild boar": 382,
                "Windsurfer": 383,
                "Zombie": 384,
                "Alpaca": 385,
                "Angler": 386,
                "Ant": 387,
                "Battery": 388,
                "Bee": 389,
                "Bicycle": 390,
                "Big": 391,
                "Bonsai tree": 392,
                "Cannon": 393,
                "Car": 394,
                "Cauldron": 395,
                "Caviar": 396,
                "Chicken coop": 397,
                "Chicken soup": 398,
                "Chicken wing": 399,
                "Christmas tree": 400,
                "Coconut": 401,
                "Combustion engine": 402,
                "Computer mouse": 403,
                "Container": 404,
                "Cook": 405,
                "Coral": 406,
                "Cyclist": 407,
                "Diamond": 408,
                "Doctor": 409,
                "Doge": 410,
                "Doghouse": 411,
                "Drone": 412,
                "Dry ice": 413,
                "Duckling": 414,
                "Engineer": 415,
                "Fairy tale": 416,
                "Faun": 417,
                "Fire extinguisher": 418,
                "Forest": 419,
                "Fox": 420,
                "Fruit": 421,
                "Gardener": 422,
                "Gnome": 423,
                "Golem": 424,
                "Hail": 425,
                "Harp": 426,
                "Hay": 427,
                "Helicopter": 428,
                "Husky": 429,
                "Internet": 430,
                "Jack-o'-lantern": 431,
                "Juice": 432,
                "Kaiju": 433,
                "Lasso": 434,
                "Lawn": 435,
                "Lawn mower": 436,
                "Leaf": 437,
                "Legend": 438,
                "Lumberjack": 439,
                "Manatee": 440,
                "Milk": 441,
                "Minotaur": 442,
                "Mold": 443,
                "Monkey": 444,
                "Mountain goat": 445,
                "Narwhal": 446,
                "Nessie": 447,
                "Net": 448,
                "Nuts": 449,
                "Oil": 450,
                "Ore": 451,
                "Paleontologist": 452,
                "Palm": 453,
                "Parachute": 454,
                "Parrot": 455,
                "Peat": 456,
                "Perfume": 457,
                "Petroleum": 458,
                "Pilot": 459,
                "Pipe": 460,
                "Pirate ship": 461,
                "Polar bear": 462,
                "Potato": 463,
                "Pterodactyl": 464,
                "Pumpkin": 465,
                "Quicksilver": 466,
                "Rabbit": 467,
                "Rivulet": 468,
                "Sand castle": 469,
                "Sap": 470,
                "Saturn": 471,
                "Scalpel": 472,
                "Scythe": 473,
                "Seal": 474,
                "Seaplane": 475,
                "Seed": 476,
                "Skateboard": 477,
                "Small": 478,
                "Snowboarder": 479,
                "Soda": 480,
                "Sphinx": 481,
                "Statue": 482,
                "Steam engine": 483,
                "Steel": 484,
                "Stream": 485,
                "Sushi": 486,
                "Swamp": 487,
                "The one ring": 488,
                "Thread": 489,
                "Treehouse": 490,
                "Trojan horse": 491,
                "Tunnel": 492,
                "Tyrannosaurus rex": 493,
                "Vase": 494,
                "Water lily": 495,
                "Wheat": 496,
                "Wood": 497,
                "Woodpecker": 498,
                "Wool": 499,
                "Yeti": 500,
                "Zoo": 501,
                "Alcohol": 502,
                "Ambulance": 503,
                "Ant farm": 504,
                "Anthill": 505,
                "Arrow": 506,
                "Aviary": 507,
                "Axe": 508,
                "Banana": 509,
                "Beehive": 510,
                "Beekeeper": 511,
                "Blood bag": 512,
                "Boat": 513,
                "Book": 514,
                "Bottle": 515,
                "Boulder": 516,
                "Bow": 517,
                "Broom": 518,
                "Bucket": 519,
                "Bus": 520,
                "Butter": 521,
                "Butterfly net": 522,
                "Campfire": 523,
                "Cart": 524,
                "Cashmere": 525,
                "Cereal": 526,
                "Chainsaw": 527,
                "Cheese": 528,
                "Christmas stocking": 529,
                "Closet": 530,
                "Coconut milk": 531,
                "Coffin": 532,
                "Cutting board": 533,
                "Drum": 534,
                "Electric car": 535,
                "Fabric": 536,
                "Fireplace": 537,
                "Firetruck": 538,
                "Flour": 539,
                "Flute": 540,
                "Fountain": 541,
                "French fries": 542,
                "Fruit tree": 543,
                "Garage": 544,
                "Grim reaper": 545,
                "Gust": 546,
                "Hay bale": 547,
                "Hill": 548,
                "Honey": 549,
                "Ice cream": 550,
                "Ice sculpture": 551,
                "Jam": 552,
                "Knife": 553,
                "Laptop": 554,
                "Little alchemy (element)": 555,
                "Log cabin": 556,
                "Maple syrup": 557,
                "Mayonnaise": 558,
                "Moon rover": 559,
                "Motorcycle": 560,
                "Needle": 561,
                "Paper": 562,
                "Peanut butter": 563,
                "Pebble": 564,
                "Pencil": 565,
                "Penicillin": 566,
                "Pinocchio": 567,
                "Pitchfork": 568,
                "Popsicle": 569,
                "Quicksand": 570,
                "Rainforest": 571,
                "Rat": 572,
                "Reindeer": 573,
                "Restaurant": 574,
                "Roller coaster": 575,
                "Rv": 576,
                "Sack": 577,
                "Santa": 578,
                "Scarecrow": 579,
                "Scuba tank": 580,
                "Sewing machine": 581,
                "Shovel": 582,
                "Silo": 583,
                "Smoothie": 584,
                "Snowmobile": 585,
                "Soap": 586,
                "Spider": 587,
                "Squirrel": 588,
                "Steamboat": 589,
                "Steel wool": 590,
                "Sugar": 591,
                "Sweater": 592,
                "Tailor": 593,
                "Tank": 594,
                "Tea": 595,
                "Thermometer": 596,
                "Titanic": 597,
                "Tractor": 598,
                "Train": 599,
                "Vault": 600,
                "Water pipe": 601,
                "Witch": 602,
                "Yogurt": 603,
                "Apron": 604,
                "Armor": 605,
                "Bandage": 606,
                "Batter": 607,
                "Bbq": 608,
                "Beer": 609,
                "Box": 610,
                "Candy cane": 611,
                "Canvas": 612,
                "Caramel": 613,
                "Chocolate": 614,
                "Cigarette": 615,
                "Confetti": 616,
                "Cookbook": 617,
                "Cotton candy": 618,
                "Crayon": 619,
                "Cup": 620,
                "Diver": 621,
                "Dough": 622,
                "Drunk": 623,
                "Excavator": 624,
                "Flying squirrel": 625,
                "Fork": 626,
                "Frozen yogurt": 627,
                "Gift": 628,
                "Hamburger": 629,
                "Hamster": 630,
                "Hedgehog": 631,
                "Ice cream truck": 632,
                "Iced tea": 633,
                "Jar": 634,
                "Kite": 635,
                "Letter": 636,
                "Library": 637,
                "Map": 638,
                "Marshmallows": 639,
                "Milk shake": 640,
                "Money": 641,
                "Mouse": 642,
                "Mousetrap": 643,
                "Musician": 644,
                "Newspaper": 645,
                "Orchard": 646,
                "Origami": 647,
                "Pan flute": 648,
                "Paper airplane": 649,
                "Pasta": 650,
                "Pencil sharpener": 651,
                "Pizza": 652,
                "Printer": 653,
                "Recipe": 654,
                "Robot vacuum": 655,
                "Rock": 656,
                "Ruler": 657,
                "Sailboat": 658,
                "Sandpaper": 659,
                "Sleigh": 660,
                "Smoke signal": 661,
                "Spoon": 662,
                "Sprinkles": 663,
                "Syringe": 664,
                "Tablet": 665,
                "Tent": 666,
                "Trainyard": 667,
                "Vacuum cleaner": 668,
                "Vine": 669,
                "Wagon": 670,
                "Wax": 671,
                "Web": 672,
                "Wine": 673,
                "Wrapping paper": 674,
                "Writer": 675,
                "Armadillo": 676,
                "Baker": 677,
                "Banana bread": 678,
                "Barrel": 679,
                "Bat": 680,
                "Bread": 681,
                "Bulletproof vest": 682,
                "Candle": 683,
                "Cheeseburger": 684,
                "Chocolate milk": 685,
                "Circus": 686,
                "Cookie cutter": 687,
                "Cookie dough": 688,
                "Donut": 689,
                "Email": 690,
                "Gingerbread house": 691,
                "Gingerbread man": 692,
                "Hot chocolate": 693,
                "Librarian": 694,
                "Mac and cheese": 695,
                "Mail truck": 696,
                "Mailbox": 697,
                "Mailman": 698,
                "Music": 699,
                "Painting": 700,
                "Paper cup": 701,
                "Paraglider": 702,
                "Pie": 703,
                "Post office": 704,
                "Smartphone": 705,
                "Spaghetti": 706,
                "String phone": 707,
                "Treasure map": 708,
                "Vinegar": 709,
                "Bakery": 710,
                "Cake": 711,
                "Cookie": 712,
                "Fortune cookie": 713,
                "Sandwich": 714,
                "Sheet music": 715,
                "Toast": 716,
                "Treasure": 717,
                "Grilled cheese": 718,
                "Picnic": 719,
}
