mapperElmIdx = {0: 'Air',
                1: 'Earth',
                2: 'Fire',
                3: 'Water',
                4: 'Time',
                5: 'Dust',
                6: 'Energy',
                7: 'Land',
                8: 'Lava',
                9: 'Mist',
                10: 'Mud',
                11: 'Pressure',
                12: 'Puddle',
                13: 'Smoke',
                14: 'Steam',
                15: 'Brick',
                16: 'Continent',
                17: 'Earthquake',
                18: 'Eruption',
                19: 'Geyser',
                20: 'Granite',
                21: 'Gunpowder',
                22: 'Heat',
                23: 'Obsidian',
                24: 'Pond',
                25: 'Stone',
                26: 'Volcano',
                27: 'Wind',
                28: 'Chimney',
                29: 'Clay',
                30: 'Explosion',
                31: 'Lake',
                32: 'Metal',
                33: 'Mountain',
                34: 'Planet',
                35: 'Plasma',
                36: 'Sand',
                37: 'Tornado',
                38: 'Wall',
                39: 'Warmth',
                40: 'Atmosphere',
                41: 'Atomic bomb',
                42: 'Avalanche',
                43: 'Beach',
                44: 'Blade',
                45: 'Boiler',
                46: 'Bullet',
                47: 'Dam',
                48: 'Desert',
                49: 'Dune',
                50: 'Firewall',
                51: 'Glass',
                52: 'Gold',
                53: 'Grenade',
                54: 'House',
                55: 'Mercury',
                56: 'Moon',
                57: 'Mountain range',
                58: 'Plow',
                59: 'River',
                60: 'Rust',
                61: 'Sandstone',
                62: 'Sandstorm',
                63: 'Sea',
                64: 'Solar system',
                65: 'Sun',
                66: 'Venus',
                67: 'Waterfall',
                68: 'Wave',
                69: 'Aquarium',
                70: 'Aurora',
                71: 'Bank',
                72: 'Black hole',
                73: 'Blender',
                74: 'Bridge',
                75: 'Cloud',
                76: 'Current',
                77: 'Eclipse',
                78: 'Factory',
                79: 'Field',
                80: 'Fireworks',
                81: 'Flood',
                82: 'Galaxy',
                83: 'Glasses',
                84: 'Gun',
                85: 'Hourglass',
                86: 'Hurricane',
                87: 'Island',
                88: 'Katana',
                89: 'Mars',
                90: 'Meteoroid',
                91: 'Mirror',
                92: 'Oasis',
                93: 'Ocean',
                94: 'Primordial soup',
                95: 'Pyramid',
                96: 'Rainbow',
                97: 'Rocket',
                98: 'Safe',
                99: 'Salt',
                100: 'Scissors',
                101: 'Sky',
                102: 'Solar cell',
                103: 'Sound',
                104: 'Space station',
                105: 'Supernova',
                106: 'Swimming pool',
                107: 'Sword',
                108: 'Telescope',
                109: 'Tide',
                110: 'Tsunami',
                111: 'Village',
                112: 'Windmill',
                113: 'Acid rain',
                114: 'Archipelago',
                115: 'Barn',
                116: 'Bayonet',
                117: 'Bell',
                118: 'Binoculars',
                119: 'City',
                120: 'Day',
                121: 'Double rainbow!',
                122: 'Electricity',
                123: 'Excalibur',
                124: 'Fence',
                125: 'Flamethrower',
                126: 'Fog',
                127: 'Galaxy cluster',
                128: 'Hangar',
                129: 'Horizon',
                130: 'Jupiter',
                131: 'Life',
                132: 'Light sword',
                133: 'Lightning',
                134: 'Meteor',
                135: 'Night',
                136: 'Paint',
                137: 'Park',
                138: 'Prism',
                139: 'Rain',
                140: 'Ruins',
                141: 'Safety glasses',
                142: 'Skyscraper',
                143: 'Space',
                144: 'Storm',
                145: 'Stun gun',
                146: 'Sunglasses',
                147: 'Swim goggles',
                148: 'Water gun',
                149: 'Alien',
                150: 'Animal',
                151: 'Bacteria',
                152: 'Clock',
                153: 'Darkness',
                154: 'Dawn',
                155: 'Death',
                156: 'Farm',
                157: 'Human',
                158: 'Light bulb',
                159: 'Magic',
                160: 'Ozone',
                161: 'Phoenix',
                162: 'Plankton',
                163: 'Robot',
                164: 'Smog',
                165: 'Snow',
                166: 'Soil',
                167: 'Spaceship',
                168: 'Star',
                169: 'Twilight',
                170: 'Universe',
                171: 'Wind turbine',
                172: 'Wire',
                173: 'Alarm clock',
                174: 'Alchemist',
                175: 'Allergy',
                176: 'Antarctica',
                177: 'Archeologist',
                178: 'Astronaut',
                179: 'Astronomer',
                180: 'Beaver',
                181: 'Bird',
                182: 'Blizzard',
                183: 'Blood',
                184: 'Butterfly',
                185: 'Cable car',
                186: 'Camel',
                187: 'Cat',
                188: 'Chain',
                189: 'Cold',
                190: 'Constellation',
                191: 'Corpse',
                192: 'Crystal ball',
                193: 'Cyborg',
                194: 'Dew',
                195: 'Domestication',
                196: 'Dynamite',
                197: 'Egg',
                198: 'Electrician',
                199: 'Family',
                200: 'Farmer',
                201: 'Firefighter',
                202: 'Fish',
                203: 'Force knight',
                204: 'Frog',
                205: 'Glacier',
                206: 'Gravestone',
                207: 'Hacker',
                208: 'Hero',
                209: 'Horse',
                210: 'Idea',
                211: 'Igloo',
                212: 'Lamp',
                213: 'Light',
                214: 'Livestock',
                215: 'Lizard',
                216: 'Love',
                217: 'Meat',
                218: 'Microscope',
                219: 'Monarch',
                220: 'Mummy',
                221: 'Organic matter',
                222: 'Painter',
                223: 'Pig',
                224: 'Plant',
                225: 'Potter',
                226: 'Sailor',
                227: 'Samurai',
                228: 'Science',
                229: 'Scorpion',
                230: 'Shuriken',
                231: 'Sickness',
                232: 'Ski goggles',
                233: 'Skier',
                234: 'Sloth',
                235: 'Snake',
                236: 'Snow globe',
                237: 'Snowball',
                238: 'Snowman',
                239: 'Starfish',
                240: 'Sundial',
                241: 'Surfer',
                242: 'Swimmer',
                243: 'Tool',
                244: 'Turtle',
                245: 'Ufo',
                246: 'Warrior',
                247: 'Watch',
                248: 'Wizard',
                249: 'Wolf',
                250: 'Airplane',
                251: 'Algae',
                252: 'Alligator',
                253: 'Angel',
                254: 'Arctic',
                255: 'Ash',
                256: 'Bacon',
                257: 'Birdcage',
                258: 'Birdhouse',
                259: 'Bone',
                260: 'Butcher',
                261: 'Cactus',
                262: 'Cage',
                263: 'Carbon dioxide',
                264: 'Carrot',
                265: 'Castle',
                266: 'Catnip',
                267: 'Cave',
                268: 'Centaur',
                269: 'Chameleon',
                270: 'Charcoal',
                271: 'Chicken',
                272: 'Chill',
                273: 'Coal',
                274: 'Computer',
                275: 'Cotton',
                276: 'Cow',
                277: 'Crow',
                278: 'Cuckoo',
                279: 'Dinosaur',
                280: 'Dog',
                281: 'Don quixote',
                282: 'Dragon',
                283: 'Duck',
                284: 'Eagle',
                285: 'Egg timer',
                286: 'Electric eel',
                287: 'Family tree',
                288: 'Firestation',
                289: 'Fishing rod',
                290: 'Flashlight',
                291: 'Flower',
                292: 'Flying fish',
                293: 'Fossil',
                294: "Frankenstein's monster",
                295: 'Fridge',
                296: 'Garden',
                297: 'Gas',
                298: 'Ghost',
                299: 'Goat',
                300: 'Grass',
                301: 'Grave',
                302: 'Graveyard',
                303: 'Greenhouse',
                304: 'Ham',
                305: 'Hammer',
                306: 'Hedge',
                307: 'Hippo',
                308: 'Horseshoe',
                309: 'Hospital',
                310: 'Hummingbird',
                311: 'Ice',
                312: 'Iceberg',
                313: 'Ivy',
                314: 'Jerky',
                315: 'Knight',
                316: 'Lava lamp',
                317: 'Leather',
                318: 'Lens',
                319: 'Lighthouse',
                320: 'Lion',
                321: 'Liquid',
                322: 'Machine',
                323: 'Magma',
                324: 'Medusa',
                325: 'Mermaid',
                326: 'Mineral',
                327: 'Moss',
                328: 'Moth',
                329: 'Motion',
                330: 'Nest',
                331: 'Ninja',
                332: 'Ninja turtle',
                333: 'Omelette',
                334: 'Optical fiber',
                335: 'Ostrich',
                336: 'Owl',
                337: 'Oxygen',
                338: 'Peacock',
                339: 'Pegasus',
                340: 'Penguin',
                341: 'Philosophy',
                342: 'Pigeon',
                343: 'Piggy bank',
                344: 'Piranha',
                345: 'Pirate',
                346: 'Platypus',
                347: 'Pollen',
                348: 'Pottery',
                349: 'Reed',
                350: 'Ring',
                351: 'Roe',
                352: 'Rope',
                353: 'Rose',
                354: 'Saddle',
                355: 'Seagull',
                356: 'Seahorse',
                357: 'Seasickness',
                358: 'Seaweed',
                359: 'Shark',
                360: 'Sheep',
                361: 'Skeleton',
                362: 'Snowboard',
                363: 'Solid',
                364: 'Spotlight',
                365: 'Steak',
                366: 'Stethoscope',
                367: 'Story',
                368: 'Sunflower',
                369: 'Swordfish',
                370: 'Tobacco',
                371: 'Toolbox',
                372: 'Toucan',
                373: 'Tree',
                374: 'Umbrella',
                375: 'Unicorn',
                376: 'Vampire',
                377: 'Vegetable',
                378: 'Vulture',
                379: 'Wand',
                380: 'Werewolf',
                381: 'Wheel',
                382: 'Wild boar',
                383: 'Windsurfer',
                384: 'Zombie',
                385: 'Alpaca',
                386: 'Angler',
                387: 'Ant',
                388: 'Battery',
                389: 'Bee',
                390: 'Bicycle',
                391: 'Big',
                392: 'Bonsai tree',
                393: 'Cannon',
                394: 'Car',
                395: 'Cauldron',
                396: 'Caviar',
                397: 'Chicken coop',
                398: 'Chicken soup',
                399: 'Chicken wing',
                400: 'Christmas tree',
                401: 'Coconut',
                402: 'Combustion engine',
                403: 'Computer mouse',
                404: 'Container',
                405: 'Cook',
                406: 'Coral',
                407: 'Cyclist',
                408: 'Diamond',
                409: 'Doctor',
                410: 'Doge',
                411: 'Doghouse',
                412: 'Drone',
                413: 'Dry ice',
                414: 'Duckling',
                415: 'Engineer',
                416: 'Fairy tale',
                417: 'Faun',
                418: 'Fire extinguisher',
                419: 'Forest',
                420: 'Fox',
                421: 'Fruit',
                422: 'Gardener',
                423: 'Gnome',
                424: 'Golem',
                425: 'Hail',
                426: 'Harp',
                427: 'Hay',
                428: 'Helicopter',
                429: 'Husky',
                430: 'Internet',
                431: "Jack-o'-lantern",
                432: 'Juice',
                433: 'Kaiju',
                434: 'Lasso',
                435: 'Lawn',
                436: 'Lawn mower',
                437: 'Leaf',
                438: 'Legend',
                439: 'Lumberjack',
                440: 'Manatee',
                441: 'Milk',
                442: 'Minotaur',
                443: 'Mold',
                444: 'Monkey',
                445: 'Mountain goat',
                446: 'Narwhal',
                447: 'Nessie',
                448: 'Net',
                449: 'Nuts',
                450: 'Oil',
                451: 'Ore',
                452: 'Paleontologist',
                453: 'Palm',
                454: 'Parachute',
                455: 'Parrot',
                456: 'Peat',
                457: 'Perfume',
                458: 'Petroleum',
                459: 'Pilot',
                460: 'Pipe',
                461: 'Pirate ship',
                462: 'Polar bear',
                463: 'Potato',
                464: 'Pterodactyl',
                465: 'Pumpkin',
                466: 'Quicksilver',
                467: 'Rabbit',
                468: 'Rivulet',
                469: 'Sand castle',
                470: 'Sap',
                471: 'Saturn',
                472: 'Scalpel',
                473: 'Scythe',
                474: 'Seal',
                475: 'Seaplane',
                476: 'Seed',
                477: 'Skateboard',
                478: 'Small',
                479: 'Snowboarder',
                480: 'Soda',
                481: 'Sphinx',
                482: 'Statue',
                483: 'Steam engine',
                484: 'Steel',
                485: 'Stream',
                486: 'Sushi',
                487: 'Swamp',
                488: 'The one ring',
                489: 'Thread',
                490: 'Treehouse',
                491: 'Trojan horse',
                492: 'Tunnel',
                493: 'Tyrannosaurus rex',
                494: 'Vase',
                495: 'Water lily',
                496: 'Wheat',
                497: 'Wood',
                498: 'Woodpecker',
                499: 'Wool',
                500: 'Yeti',
                501: 'Zoo',
                502: 'Alcohol',
                503: 'Ambulance',
                504: 'Ant farm',
                505: 'Anthill',
                506: 'Arrow',
                507: 'Aviary',
                508: 'Axe',
                509: 'Banana',
                510: 'Beehive',
                511: 'Beekeeper',
                512: 'Blood bag',
                513: 'Boat',
                514: 'Book',
                515: 'Bottle',
                516: 'Boulder',
                517: 'Bow',
                518: 'Broom',
                519: 'Bucket',
                520: 'Bus',
                521: 'Butter',
                522: 'Butterfly net',
                523: 'Campfire',
                524: 'Cart',
                525: 'Cashmere',
                526: 'Cereal',
                527: 'Chainsaw',
                528: 'Cheese',
                529: 'Christmas stocking',
                530: 'Closet',
                531: 'Coconut milk',
                532: 'Coffin',
                533: 'Cutting board',
                534: 'Drum',
                535: 'Electric car',
                536: 'Fabric',
                537: 'Fireplace',
                538: 'Firetruck',
                539: 'Flour',
                540: 'Flute',
                541: 'Fountain',
                542: 'French fries',
                543: 'Fruit tree',
                544: 'Garage',
                545: 'Grim reaper',
                546: 'Gust',
                547: 'Hay bale',
                548: 'Hill',
                549: 'Honey',
                550: 'Ice cream',
                551: 'Ice sculpture',
                552: 'Jam',
                553: 'Knife',
                554: 'Laptop',
                555: 'Little alchemy (element)',
                556: 'Log cabin',
                557: 'Maple syrup',
                558: 'Mayonnaise',
                559: 'Moon rover',
                560: 'Motorcycle',
                561: 'Needle',
                562: 'Paper',
                563: 'Peanut butter',
                564: 'Pebble',
                565: 'Pencil',
                566: 'Penicillin',
                567: 'Pinocchio',
                568: 'Pitchfork',
                569: 'Popsicle',
                570: 'Quicksand',
                571: 'Rainforest',
                572: 'Rat',
                573: 'Reindeer',
                574: 'Restaurant',
                575: 'Roller coaster',
                576: 'Rv',
                577: 'Sack',
                578: 'Santa',
                579: 'Scarecrow',
                580: 'Scuba tank',
                581: 'Sewing machine',
                582: 'Shovel',
                583: 'Silo',
                584: 'Smoothie',
                585: 'Snowmobile',
                586: 'Soap',
                587: 'Spider',
                588: 'Squirrel',
                589: 'Steamboat',
                590: 'Steel wool',
                591: 'Sugar',
                592: 'Sweater',
                593: 'Tailor',
                594: 'Tank',
                595: 'Tea',
                596: 'Thermometer',
                597: 'Titanic',
                598: 'Tractor',
                599: 'Train',
                600: 'Vault',
                601: 'Water pipe',
                602: 'Witch',
                603: 'Yogurt',
                604: 'Apron',
                605: 'Armor',
                606: 'Bandage',
                607: 'Batter',
                608: 'Bbq',
                609: 'Beer',
                610: 'Box',
                611: 'Candy cane',
                612: 'Canvas',
                613: 'Caramel',
                614: 'Chocolate',
                615: 'Cigarette',
                616: 'Confetti',
                617: 'Cookbook',
                618: 'Cotton candy',
                619: 'Crayon',
                620: 'Cup',
                621: 'Diver',
                622: 'Dough',
                623: 'Drunk',
                624: 'Excavator',
                625: 'Flying squirrel',
                626: 'Fork',
                627: 'Frozen yogurt',
                628: 'Gift',
                629: 'Hamburger',
                630: 'Hamster',
                631: 'Hedgehog',
                632: 'Ice cream truck',
                633: 'Iced tea',
                634: 'Jar',
                635: 'Kite',
                636: 'Letter',
                637: 'Library',
                638: 'Map',
                639: 'Marshmallows',
                640: 'Milk shake',
                641: 'Money',
                642: 'Mouse',
                643: 'Mousetrap',
                644: 'Musician',
                645: 'Newspaper',
                646: 'Orchard',
                647: 'Origami',
                648: 'Pan flute',
                649: 'Paper airplane',
                650: 'Pasta',
                651: 'Pencil sharpener',
                652: 'Pizza',
                653: 'Printer',
                654: 'Recipe',
                655: 'Robot vacuum',
                656: 'Rock',
                657: 'Ruler',
                658: 'Sailboat',
                659: 'Sandpaper',
                660: 'Sleigh',
                661: 'Smoke signal',
                662: 'Spoon',
                663: 'Sprinkles',
                664: 'Syringe',
                665: 'Tablet',
                666: 'Tent',
                667: 'Trainyard',
                668: 'Vacuum cleaner',
                669: 'Vine',
                670: 'Wagon',
                671: 'Wax',
                672: 'Web',
                673: 'Wine',
                674: 'Wrapping paper',
                675: 'Writer',
                676: 'Armadillo',
                677: 'Baker',
                678: 'Banana bread',
                679: 'Barrel',
                680: 'Bat',
                681: 'Bread',
                682: 'Bulletproof vest',
                683: 'Candle',
                684: 'Cheeseburger',
                685: 'Chocolate milk',
                686: 'Circus',
                687: 'Cookie cutter',
                688: 'Cookie dough',
                689: 'Donut',
                690: 'Email',
                691: 'Gingerbread house',
                692: 'Gingerbread man',
                693: 'Hot chocolate',
                694: 'Librarian',
                695: 'Mac and cheese',
                696: 'Mail truck',
                697: 'Mailbox',
                698: 'Mailman',
                699: 'Music',
                700: 'Painting',
                701: 'Paper cup',
                702: 'Paraglider',
                703: 'Pie',
                704: 'Post office',
                705: 'Smartphone',
                706: 'Spaghetti',
                707: 'String phone',
                708: 'Treasure map',
                709: 'Vinegar',
                710: 'Bakery',
                711: 'Cake',
                712: 'Cookie',
                713: 'Fortune cookie',
                714: 'Sandwich',
                715: 'Sheet music',
                716: 'Toast',
                717: 'Treasure',
                718: 'Grilled cheese',
                719: 'Picnic'
}
